server:
  port: 9000
  servlet:
    context-path: /pay

spring:
  thymeleaf:
    cache: false
  application:
    name: jcb-pay
  data:
    redis:
      port: 6379
      host: 192.168.35.108
      password: 123456

dubbo:
  application:
    name: jcb-pay
    qos-enable: false
    serialize-check-status: WARN
  protocol:
    name: dubbo
    port: 20883
  registry:
    address: zookeeper://192.168.35.108:2181
  scan:
    base-packages: com.xytx
  consumer:
    check: false
    timeout: 50000
    retries: 0
