package com.xytx.mapper;

import com.xytx.moder.BIncomeRecord;
import com.xytx.vo.IncomeRecordVo;

import java.util.Date;
import java.util.List;

public interface BIncomeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jcb..b_income_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jcb..b_income_record
     *
     * @mbg.generated
     */
    int insert(BIncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jcb..b_income_record
     *
     * @mbg.generated
     */
    int insertSelective(BIncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jcb..b_income_record
     *
     * @mbg.generated
     */
    BIncomeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jcb..b_income_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BIncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jcb..b_income_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BIncomeRecord record);

    List<IncomeRecordVo> selectByUid(Integer userId);

    List<BIncomeRecord> selectExpiredIncome(Date expiredDate);
}