package com.xytx.moder;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   投资记录表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table jcb..b_bid_info
 */
@Data
public class BBidInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   投标记录ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_bid_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   产品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_bid_info.prod_id
     *
     * @mbg.generated
     */
    private Integer prodId;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_bid_info.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   投标金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_bid_info.bid_money
     *
     * @mbg.generated
     */
    private BigDecimal bidMoney;

    /**
     * Database Column Remarks:
     *   投标时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_bid_info.bid_time
     *
     * @mbg.generated
     */
    private Date bidTime;

    /**
     * Database Column Remarks:
     *   投标状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_bid_info.bid_status
     *
     * @mbg.generated
     */
    private Integer bidStatus;
}