package com.xytx.moder;

import com.xytx.pojo.BidInfoProduct;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * Database Table Remarks:
 *   产品信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table jcb..b_product_record
 */
@Data
public class BProductRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   产品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   产品利率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.rate
     *
     * @mbg.generated
     */
    private BigDecimal rate;

    /**
     * Database Column Remarks:
     *   产品期限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.cycle
     *
     * @mbg.generated
     */
    private Integer cycle;

    /**
     * Database Column Remarks:
     *   产品发布时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.release_time
     *
     * @mbg.generated
     */
    private Date releaseTime;

    /**
     * Database Column Remarks:
     *   产品类型 0新手宝，1优选产品，2散标产品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.product_type
     *
     * @mbg.generated
     */
    private Integer productType;

    /**
     * Database Column Remarks:
     *   产品编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.product_no
     *
     * @mbg.generated
     */
    private String productNo;

    /**
     * Database Column Remarks:
     *   产品金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.product_money
     *
     * @mbg.generated
     */
    private BigDecimal productMoney;

    /**
     * Database Column Remarks:
     *   产品剩余可投金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.left_product_money
     *
     * @mbg.generated
     */
    private BigDecimal leftProductMoney;

    /**
     * Database Column Remarks:
     *   最低投资金额，即起投金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.bid_min_limit
     *
     * @mbg.generated
     */
    private BigDecimal bidMinLimit;

    /**
     * Database Column Remarks:
     *   最高投资金额，即最多能投多少金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.bid_max_limit
     *
     * @mbg.generated
     */
    private BigDecimal bidMaxLimit;

    /**
     * Database Column Remarks:
     *   产品状态（0未满标，1已满标，2满标已生成收益计划）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.product_status
     *
     * @mbg.generated
     */
    private Integer productStatus;

    /**
     * Database Column Remarks:
     *   产品投资满标时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.product_full_time
     *
     * @mbg.generated
     */
    private Date productFullTime;

    /**
     * Database Column Remarks:
     *   产品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_product_record.product_desc
     *
     * @mbg.generated
     */
    private String productDesc;

    private List<BidInfoProduct> bidInfoProducts;

}