package com.xytx.moder;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   充值记录表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table jcb..b_recharge_record
 */
@Data
public class BRechargeRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_recharge_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_recharge_record.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   充值订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_recharge_record.recharge_no
     *
     * @mbg.generated
     */
    private String rechargeNo;

    /**
     * Database Column Remarks:
     *   充值订单状态（0充值中，1充值成功，2充值失败）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_recharge_record.recharge_status
     *
     * @mbg.generated
     */
    private Integer rechargeStatus;

    /**
     * Database Column Remarks:
     *   充值金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_recharge_record.recharge_money
     *
     * @mbg.generated
     */
    private BigDecimal rechargeMoney;

    /**
     * Database Column Remarks:
     *   充值时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_recharge_record.recharge_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date rechargeTime;

    /**
     * Database Column Remarks:
     *   充值描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_recharge_record.recharge_desc
     *
     * @mbg.generated
     */
    private String rechargeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..b_recharge_record.channel
     *
     * @mbg.generated
     */
    private String channel;
}