package com.xytx.moder;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   用户财务资金账户表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table jcb..u_finance_account
 */
@Data
public class UFinanceAccount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..u_finance_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..u_finance_account.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   用户可用资金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..u_finance_account.available_money
     *
     * @mbg.generated
     */
    private BigDecimal availableMoney;
}