package com.xytx.moder;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   用户表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table jcb..u_user
 */
@Data
public class UUser implements Serializable {
    /**
     * Database Column Remarks:
     *   用户id,主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..u_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   注册手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..u_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   登陆密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..u_user.login_password
     *
     * @mbg.generated
     */
    private String loginPassword;

    /**
     * Database Column Remarks:
     *   用户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..u_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   用户身份证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..u_user.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     * Database Column Remarks:
     *   注册时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..u_user.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     * Database Column Remarks:
     *   最近登录时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..u_user.last_login_time
     *
     * @mbg.generated
     */
    private Date lastLoginTime;

    /**
     * Database Column Remarks:
     *   用户头像文件路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jcb..u_user.header_image
     *
     * @mbg.generated
     */
    private String headerImage;
}